name: weather_app_pt
description: 'Weather app'
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.0-290.4.beta

dependencies:
  envied: ^1.3.1
  flutter:
    sdk: flutter
  http: ^1.6.0

dev_dependencies:
  build_runner: ^2.10.3
  envied_generator: ^1.3.1
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  very_good_analysis: ^10.0.0

flutter:
  uses-material-design: true
