name: weather_app_pt
description: 'Weather app'
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.0-290.4.beta

dependencies:
  envied: ^1.3.1
  flutter:
    sdk: flutter
  flutter_riverpod: ^3.0.3
  http: ^1.6.0
  riverpod: ^3.0.3
  riverpod_annotation: ^3.0.3

dev_dependencies:
  build_runner: ^2.10.3
  custom_lint: ^0.8.1
  envied_generator: ^1.3.1
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  riverpod_generator: ^3.0.3
  riverpod_lint: ^3.0.3
  very_good_analysis: ^10.0.0

flutter:
  uses-material-design: true
